package io.mycat.ice.domain;

import java.util.Date;

public class IceProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_project.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_project.OWNER
     *
     * @mbggenerated
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_project.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_project.VERSION
     *
     * @mbggenerated
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_project.ICE_VERSION
     *
     * @mbggenerated
     */
    private String iceVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_project.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_project.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_project.XML_SPEC
     *
     * @mbggenerated
     */
    private String xmlSpec;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_project.ID
     *
     * @return the value of ice_project.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_project.ID
     *
     * @param id the value for ice_project.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_project.OWNER
     *
     * @return the value of ice_project.OWNER
     *
     * @mbggenerated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_project.OWNER
     *
     * @param owner the value for ice_project.OWNER
     *
     * @mbggenerated
     */
    public void setOwner(String owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_project.NAME
     *
     * @return the value of ice_project.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_project.NAME
     *
     * @param name the value for ice_project.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_project.VERSION
     *
     * @return the value of ice_project.VERSION
     *
     * @mbggenerated
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_project.VERSION
     *
     * @param version the value for ice_project.VERSION
     *
     * @mbggenerated
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_project.ICE_VERSION
     *
     * @return the value of ice_project.ICE_VERSION
     *
     * @mbggenerated
     */
    public String getIceVersion() {
        return iceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_project.ICE_VERSION
     *
     * @param iceVersion the value for ice_project.ICE_VERSION
     *
     * @mbggenerated
     */
    public void setIceVersion(String iceVersion) {
        this.iceVersion = iceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_project.NOTE
     *
     * @return the value of ice_project.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_project.NOTE
     *
     * @param note the value for ice_project.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_project.LAST_UPDATED
     *
     * @return the value of ice_project.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_project.LAST_UPDATED
     *
     * @param lastUpdated the value for ice_project.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_project.XML_SPEC
     *
     * @return the value of ice_project.XML_SPEC
     *
     * @mbggenerated
     */
    public String getXmlSpec() {
        return xmlSpec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_project.XML_SPEC
     *
     * @param xmlSpec the value for ice_project.XML_SPEC
     *
     * @mbggenerated
     */
    public void setXmlSpec(String xmlSpec) {
        this.xmlSpec = xmlSpec;
    }
}