package io.mycat.ice.domain;

import java.util.Date;

public class IceProjIceboxInst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_proj_icebox_inst.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_proj_icebox_inst.PROJECTID
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_proj_icebox_inst.PROJECT_INSTANCE_ID
     *
     * @mbggenerated
     */
    private Integer projectInstanceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_proj_icebox_inst.SERVER_NAME
     *
     * @mbggenerated
     */
    private String serverName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_proj_icebox_inst.REPLICA
     *
     * @mbggenerated
     */
    private Byte replica;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_proj_icebox_inst.NOTE
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ice_proj_icebox_inst.LAST_UPDATED
     *
     * @mbggenerated
     */
    private Date lastUpdated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_proj_icebox_inst.ID
     *
     * @return the value of ice_proj_icebox_inst.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_proj_icebox_inst.ID
     *
     * @param id the value for ice_proj_icebox_inst.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_proj_icebox_inst.PROJECTID
     *
     * @return the value of ice_proj_icebox_inst.PROJECTID
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_proj_icebox_inst.PROJECTID
     *
     * @param projectid the value for ice_proj_icebox_inst.PROJECTID
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_proj_icebox_inst.PROJECT_INSTANCE_ID
     *
     * @return the value of ice_proj_icebox_inst.PROJECT_INSTANCE_ID
     *
     * @mbggenerated
     */
    public Integer getProjectInstanceId() {
        return projectInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_proj_icebox_inst.PROJECT_INSTANCE_ID
     *
     * @param projectInstanceId the value for ice_proj_icebox_inst.PROJECT_INSTANCE_ID
     *
     * @mbggenerated
     */
    public void setProjectInstanceId(Integer projectInstanceId) {
        this.projectInstanceId = projectInstanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_proj_icebox_inst.SERVER_NAME
     *
     * @return the value of ice_proj_icebox_inst.SERVER_NAME
     *
     * @mbggenerated
     */
    public String getServerName() {
        return serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_proj_icebox_inst.SERVER_NAME
     *
     * @param serverName the value for ice_proj_icebox_inst.SERVER_NAME
     *
     * @mbggenerated
     */
    public void setServerName(String serverName) {
        this.serverName = serverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_proj_icebox_inst.REPLICA
     *
     * @return the value of ice_proj_icebox_inst.REPLICA
     *
     * @mbggenerated
     */
    public Byte getReplica() {
        return replica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_proj_icebox_inst.REPLICA
     *
     * @param replica the value for ice_proj_icebox_inst.REPLICA
     *
     * @mbggenerated
     */
    public void setReplica(Byte replica) {
        this.replica = replica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_proj_icebox_inst.NOTE
     *
     * @return the value of ice_proj_icebox_inst.NOTE
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_proj_icebox_inst.NOTE
     *
     * @param note the value for ice_proj_icebox_inst.NOTE
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ice_proj_icebox_inst.LAST_UPDATED
     *
     * @return the value of ice_proj_icebox_inst.LAST_UPDATED
     *
     * @mbggenerated
     */
    public Date getLastUpdated() {
        return lastUpdated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ice_proj_icebox_inst.LAST_UPDATED
     *
     * @param lastUpdated the value for ice_proj_icebox_inst.LAST_UPDATED
     *
     * @mbggenerated
     */
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }
}