package io.mycat.ice.mapping;

import io.mycat.ice.domain.IceCluster;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;

public interface IceClusterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_cluster
     *
     * @mbggenerated
     */
    @Delete({
        "delete from ice_cluster",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_cluster
     *
     * @mbggenerated
     */
    @Insert({
        "insert into ice_cluster (ID, NAME, LABELS, ",
        "ICE_VERSION, INSTALL_TYPE, ",
        "NOTE, LAST_UPDATED)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=CHAR}, #{labels,jdbcType=VARCHAR}, ",
        "#{iceVersion,jdbcType=CHAR}, #{installType,jdbcType=TINYINT}, ",
        "#{note,jdbcType=VARCHAR}, #{lastUpdated,jdbcType=TIMESTAMP})"
    })
    int insert(IceCluster record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_cluster
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, NAME, LABELS, ICE_VERSION, INSTALL_TYPE, NOTE, LAST_UPDATED",
        "from ice_cluster",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="NAME", property="name", jdbcType=JdbcType.CHAR),
        @Result(column="LABELS", property="labels", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICE_VERSION", property="iceVersion", jdbcType=JdbcType.CHAR),
        @Result(column="INSTALL_TYPE", property="installType", jdbcType=JdbcType.TINYINT),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    IceCluster selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_cluster
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "ID, NAME, LABELS, ICE_VERSION, INSTALL_TYPE, NOTE, LAST_UPDATED",
        "from ice_cluster"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="NAME", property="name", jdbcType=JdbcType.CHAR),
        @Result(column="LABELS", property="labels", jdbcType=JdbcType.VARCHAR),
        @Result(column="ICE_VERSION", property="iceVersion", jdbcType=JdbcType.CHAR),
        @Result(column="INSTALL_TYPE", property="installType", jdbcType=JdbcType.TINYINT),
        @Result(column="NOTE", property="note", jdbcType=JdbcType.VARCHAR),
        @Result(column="LAST_UPDATED", property="lastUpdated", jdbcType=JdbcType.TIMESTAMP)
    })
    List<IceCluster> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ice_cluster
     *
     * @mbggenerated
     */
    @Update({
        "update ice_cluster",
        "set NAME = #{name,jdbcType=CHAR},",
          "LABELS = #{labels,jdbcType=VARCHAR},",
          "ICE_VERSION = #{iceVersion,jdbcType=CHAR},",
          "INSTALL_TYPE = #{installType,jdbcType=TINYINT},",
          "NOTE = #{note,jdbcType=VARCHAR},",
          "LAST_UPDATED = #{lastUpdated,jdbcType=TIMESTAMP}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(IceCluster record);
}